# Homework 2: NBA Season Statistics Report


**Student:** Sirui Zhang  
**Course:** QMSS / Homework 2

In [5]:

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

nba = pd.read_csv(r'C:\Users\sirui\Downloads\Seasons_Stats_NBA.csv')

numeric_cols = ['Year', 'Age', 'PTS', 'FTA', 'FT%']
for col in numeric_cols:
    nba[col] = pd.to_numeric(nba[col], errors='coerce')

print("Shape:", nba.shape)
print("\nColumns:")
print(nba.columns.tolist())

Shape: (24691, 52)

Columns:
['Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2', 'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [ ]:

nba.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,NaN,0.467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,3.6,3.5,NaN,NaN,NaN,NaN,NaN,NaN,144.0,516.0,0.279,NaN,NaN,NaN,144.0,516.0,0.279,0.279,170.0,241.0,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,NaN,0.387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6,0.6,2.2,NaN,NaN,NaN,NaN,NaN,NaN,102.0,274.0,0.372,NaN,NaN,NaN,102.0,274.0,0.372,0.372,75.0,106.0,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,NaN,0.259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9,2.8,3.6,NaN,NaN,NaN,NaN,NaN,NaN,174.0,499.0,0.349,NaN,NaN,NaN,174.0,499.0,0.349,0.349,90.0,129.0,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,NaN,0.395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,22.0,86.0,0.256,NaN,NaN,NaN,22.0,86.0,0.256,0.256,19.0,34.0,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,NaN,0.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,21.0,82.0,0.256,NaN,NaN,NaN,21.0,82.0,0.256,0.256,17.0,31.0,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0

In [ ]:

nba.tail()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,0.002,0.442,8.6,17.3,12.9,9.1,1.8,3.0,10.9,15.5,NaN,3.4,2.2,5.6,0.157,NaN,-0.2,2.3,2.1,1.8,253.0,443.0,0.571,0.0,1.0,0.000,253.0,442.0,0.572,0.571,133.0,196.0,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,0.006,0.247,9.2,17.0,13.2,12.2,0.7,3.3,10.2,16.5,NaN,0.5,0.6,1.0,0.094,NaN,-3.2,0.8,-2.5,-0.1,78.0,158.0,0.494,0.0,1.0,0.000,78.0,157.0,0.497,0.494,22.0,39.0,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,0.000,0.161,10.8,24.9,17.6,5.3,0.9,3.7,8.3,14.8,NaN,-0.1,0.1,0.0,-0.005,NaN,-7.8,0.4,-7.3,-0.1,10.0,31.0,0.323,0.0,0.0,NaN,10.0,31.0,0.323,0.323,3.0,5.0,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,0.448,0.181,1.9,14.2,8.0,6.1,0.9,1.5,14.4,14.4,NaN,-0.3,0.8,0.5,0.030,NaN,-3.6,-0.1,-3.7,-0.4,88.0,221.0,0.398,33.0,99.0,0.333,55.0,122.0,0.451,0.473,31.0,40.0,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,0.013,0.206,7.1,21.9,14.3,8.1,1.1,4.4,10.4,20.3,NaN,0.6,0.5,1.1,0.086,NaN,-2.7,0.3,-2.5,-0.1,126.0,238.0,0.529,0.0,3.0,0.000,126.0,235.0,0.536,0.529,32.0,49.0,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

## Q1. Which NBA player scored the most points in a single season? What season/year was this?

In [ ]:

q1 = nba.loc[[nba['PTS'].idxmax()], ['Player', 'Year', 'Tm', 'PTS']].reset_index(drop=True)

print("Answer:")
display(q1)

print("\nFirst five rows:")
display(q1.head())

print("\nLast five rows:")
display(q1.tail())

Answer:

              Player    Year   Tm     PTS
0  Wilt Chamberlain*  1962.0  PHW  4029.0

First five rows:

              Player    Year   Tm     PTS
0  Wilt Chamberlain*  1962.0  PHW  4029.0

Last five rows:

              Player    Year   Tm     PTS
0  Wilt Chamberlain*  1962.0  PHW  4029.0

## Q2. Which NBA player scored the most points in 1991?

In [ ]:

nba_1991 = nba[nba['Year'] == 1991].copy()
q2 = nba_1991.sort_values(['PTS', 'Player'], ascending=[False, True]).head(1)[['Player', 'Year', 'Tm', 'PTS']].reset_index(drop=True)

print("Answer:")
display(q2)

print("\nFirst five rows:")
display(q2.head())

print("\nLast five rows:")
display(q2.tail())

Answer:

            Player    Year   Tm     PTS
0  Michael Jordan*  1991.0  CHI  2580.0

First five rows:

            Player    Year   Tm     PTS
0  Michael Jordan*  1991.0  CHI  2580.0

Last five rows:

            Player    Year   Tm     PTS
0  Michael Jordan*  1991.0  CHI  2580.0

## Q3. Which player had the best free throw percentage (FT%) from the year 2000 to the most recent year in the data? If there are ties, sort on player name and submit the answer as a DataFrame.

In [ ]:

nba_2000_plus = nba[nba['Year'] >= 2000].copy()

best_ft = nba_2000_plus['FT%'].max()
q3 = (
    nba_2000_plus[nba_2000_plus['FT%'] == best_ft][['Player', 'Year', 'Tm', 'FTA', 'FT%']]
    .sort_values('Player')
    .reset_index(drop=True)
)

print("Best FT% from 2000 onward:", best_ft)
print("Number of tied rows:", len(q3))

print("\nFirst five rows:")
display(q3.head())

print("\nLast five rows:")
display(q3.tail())

Best FT% from 2000 onward: 1.0
Number of tied rows: 313

First five rows:

            Player    Year   Tm  FTA  FT%
0      Aaron Miles  2006.0  GSW  4.0  1.0
1  Adam Harrington  2003.0  DAL  2.0  1.0
2    Adonis Thomas  2014.0  TOT  1.0  1.0
3    Adonis Thomas  2014.0  ORL  1.0  1.0
4   Adrian Griffin  2008.0  SEA  2.0  1.0

Last five rows:

              Player    Year   Tm  FTA  FT%
308    Wesley Person  2004.0  ATL  6.0  1.0
309     Will Blalock  2007.0  DET  6.0  1.0
310      Yuta Tabuse  2005.0  PHO  4.0  1.0
311  Zarko Cabarkapa  2005.0  PHO  1.0  1.0
312  Zendon Hamilton  2003.0  TOR  2.0  1.0

## Q4. Among those with at least 50 attempts (FTA), which player had the best free throw percentage (FT%) from the year 2000 to the most recent year in the data?

In [ ]:

nba_2000_plus_50fta = nba_2000_plus[nba_2000_plus['FTA'] >= 50].copy()

best_ft_50 = nba_2000_plus_50fta['FT%'].max()
q4 = (
    nba_2000_plus_50fta[nba_2000_plus_50fta['FT%'] == best_ft_50][['Player', 'Year', 'Tm', 'FTA', 'FT%']]
    .sort_values('Player')
    .reset_index(drop=True)
)

print("Best FT% from 2000 onward among players with at least 50 FTA:", best_ft_50)
display(q4)

print("\nFirst five rows:")
display(q4.head())

print("\nLast five rows:")
display(q4.tail())

Best FT% from 2000 onward among players with at least 50 FTA: 0.988

            Player    Year   Tm   FTA    FT%
0  Terrell Brandon  2002.0  MIN  84.0  0.988

First five rows:

            Player    Year   Tm   FTA    FT%
0  Terrell Brandon  2002.0  MIN  84.0  0.988

Last five rows:

            Player    Year   Tm   FTA    FT%
0  Terrell Brandon  2002.0  MIN  84.0  0.988

## Q5. Rename the variable `Pos` to `Position`.

In [6]:

nba_q5 = nba.rename(columns={'Pos': 'Position'}).copy()

print("Columns after renaming:")
print(nba_q5.columns.tolist())

Columns after renaming:
['Year', 'Player', 'Position', 'Age', 'Tm', 'G', 'GS', 'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2', 'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

## Q6. Use this variable to create two variables called `first_position` and `second_position`.

In [ ]:

position_split = nba_q5['Position'].str.split('-', n=1, expand=True)

nba_q6 = nba_q5.copy()
nba_q6['first_position'] = position_split[0]
nba_q6['second_position'] = position_split[1]

print("First five rows:")
display(nba_q6[['Player', 'Position', 'first_position', 'second_position']].head())

print("\nLast five rows:")
display(nba_q6[['Player', 'Position', 'first_position', 'second_position']].tail())

First five rows:

            Player Position first_position second_position
0  Curly Armstrong      G-F              G               F
1     Cliff Barker       SG             SG            None
2    Leo Barnhorst       SF             SF            None
3       Ed Bartels        F              F            None
4       Ed Bartels        F              F            None

Last five rows:

                  Player Position first_position second_position
24686        Cody Zeller       PF             PF            None
24687       Tyler Zeller        C              C            None
24688  Stephen Zimmerman        C              C            None
24689        Paul Zipser       SF             SF            None
24690        Ivica Zubac        C              C            None

## Q7. Combine these two variables back into a single variable called `position_united`. Make sure to separate the two positions by `-`, as the original data field did. Present a frequency table of `position_united`.

In [ ]:

nba_q7 = nba_q6.copy()
nba_q7['position_united'] = np.where(
    nba_q7['second_position'].notna(),
    nba_q7['first_position'] + '-' + nba_q7['second_position'],
    nba_q7['first_position']
)

q7_freq = (
    nba_q7['position_united']
    .value_counts(dropna=False)
    .rename_axis('position_united')
    .reset_index(name='frequency')
)

print("First five rows:")
display(q7_freq.head())

print("\nLast five rows:")
display(q7_freq.tail())

First five rows:

  position_united  frequency
0              PF       4966
1              SG       4811
2               C       4759
3              SF       4699
4              PG       4648

Last five rows:

   position_united  frequency
19           SF-PF         21
20           SG-PF          3
21            C-SF          2
22           SF-PG          1
23           PG-SF          1

## Q8. Create two new datasets.

In [ ]:

nba_without_age = nba.drop(columns=['Age']).copy()

nba_year_player_age = nba[['Year', 'Player', 'Age']].copy()

nba_without_age['mergeid'] = range(1, len(nba_without_age) + 1)
nba_year_player_age['mergeid'] = range(1, len(nba_year_player_age) + 1)

print("Dataset 1 (without Age) - first five rows:")
display(nba_without_age.head())

print("\nDataset 1 (without Age) - last five rows:")
display(nba_without_age.tail())

print("\nDataset 2 (Year, Player, Age) - first five rows:")
display(nba_year_player_age.head())

print("\nDataset 2 (Year, Player, Age) - last five rows:")
display(nba_year_player_age.tail())

Dataset 1 (without Age) - first five rows:

,Year,Player,Pos,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,mergeid
0,1950.0,Curly Armstrong,G-F,FTW,63.0,NaN,NaN,NaN,0.368,NaN,0.467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,3.6,3.5,NaN,NaN,NaN,NaN,NaN,NaN,144.0,516.0,0.279,NaN,NaN,NaN,144.0,516.0,0.279,0.279,170.0,241.0,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0,1
1,1950.0,Cliff Barker,SG,INO,49.0,NaN,NaN,NaN,0.435,NaN,0.387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6,0.6,2.2,NaN,NaN,NaN,NaN,NaN,NaN,102.0,274.0,0.372,NaN,NaN,NaN,102.0,274.0,0.372,0.372,75.0,106.0,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0,2
2,1950.0,Leo Barnhorst,SF,CHS,67.0,NaN,NaN,NaN,0.394,NaN,0.259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9,2.8,3.6,NaN,NaN,NaN,NaN,NaN,NaN,174.0,499.0,0.349,NaN,NaN,NaN,174.0,499.0,0.349,0.349,90.0,129.0,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0,3
3,1950.0,Ed Bartels,F,TOT,15.0,NaN,NaN,NaN,0.312,NaN,0.395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,22.0,86.0,0.256,NaN,NaN,NaN,22.0,86.0,0.256,0.256,19.0,34.0,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0,4
4,1950.0,Ed Bartels,F,DNN,13.0,NaN,NaN,NaN,0.308,NaN,0.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,21.0,82.0,0.256,NaN,NaN,NaN,21.0,82.0,0.256,0.256,17.0,31.0,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0,5

Dataset 1 (without Age) - last five rows:

,Year,Player,Pos,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,mergeid
24686,2017.0,Cody Zeller,PF,CHO,62.0,58.0,1725.0,16.7,0.604,0.002,0.442,8.6,17.3,12.9,9.1,1.8,3.0,10.9,15.5,NaN,3.4,2.2,5.6,0.157,NaN,-0.2,2.3,2.1,1.8,253.0,443.0,0.571,0.0,1.0,0.000,253.0,442.0,0.572,0.571,133.0,196.0,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0,24687
24687,2017.0,Tyler Zeller,C,BOS,51.0,5.0,525.0,13.0,0.508,0.006,0.247,9.2,17.0,13.2,12.2,0.7,3.3,10.2,16.5,NaN,0.5,0.6,1.0,0.094,NaN,-3.2,0.8,-2.5,-0.1,78.0,158.0,0.494,0.0,1.0,0.000,78.0,157.0,0.497,0.494,22.0,39.0,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0,24688
24688,2017.0,Stephen Zimmerman,C,ORL,19.0,0.0,108.0,7.3,0.346,0.000,0.161,10.8,24.9,17.6,5.3,0.9,3.7,8.3,14.8,NaN,-0.1,0.1,0.0,-0.005,NaN,-7.8,0.4,-7.3,-0.1,10.0,31.0,0.323,0.0,0.0,NaN,10.0,31.0,0.323,0.323,3.0,5.0,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0,24689
24689,2017.0,Paul Zipser,SF,CHI,44.0,18.0,843.0,6.9,0.503,0.448,0.181,1.9,14.2,8.0,6.1,0.9,1.5,14.4,14.4,NaN,-0.3,0.8,0.5,0.030,NaN,-3.6,-0.1,-3.7,-0.4,88.0,221.0,0.398,33.0,99.0,0.333,55.0,122.0,0.451,0.473,31.0,40.0,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0,24690
24690,2017.0,Ivica Zubac,C,LAL,38.0,11.0,609.0,17.0,0.547,0.013,0.206,7.1,21.9,14.3,8.1,1.1,4.4,10.4,20.3,NaN,0.6,0.5,1.1,0.086,NaN,-2.7,0.3,-2.5,-0.1,126.0,238.0,0.529,0.0,3.0,0.000,126.0,235.0,0.536,0.529,32.0,49.0,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0,24691

Dataset 2 (Year, Player, Age) - first five rows:

     Year           Player   Age  mergeid
0  1950.0  Curly Armstrong  31.0        1
1  1950.0     Cliff Barker  29.0        2
2  1950.0    Leo Barnhorst  25.0        3
3  1950.0       Ed Bartels  24.0        4
4  1950.0       Ed Bartels  24.0        5

Dataset 2 (Year, Player, Age) - last five rows:

         Year             Player   Age  mergeid
24686  2017.0        Cody Zeller  24.0    24687
24687  2017.0       Tyler Zeller  27.0    24688
24688  2017.0  Stephen Zimmerman  20.0    24689
24689  2017.0        Paul Zipser  22.0    24690
24690  2017.0        Ivica Zubac  19.0    24691

## Q9. Join the two datasets from question 8 together to recreate the original dataset plus the new `mergeid`.

In [ ]:

q9_merged = pd.merge(
    nba_without_age,
    nba_year_player_age,
    on=['mergeid', 'Year', 'Player'],
    how='inner'
)

ordered_cols = ['mergeid', 'Year', 'Player', 'Age'] + [col for col in nba.columns if col not in ['Year', 'Player', 'Age']]
q9_merged = q9_merged[ordered_cols]

print("Shape of recreated dataset:", q9_merged.shape)

print("\nFirst five rows:")
display(q9_merged.head())

print("\nLast five rows:")
display(q9_merged.tail())

Shape of recreated dataset:

 (24691, 53)

First five rows:

,mergeid,Year,Player,Age,Pos,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,1950.0,Curly Armstrong,31.0,G-F,FTW,63.0,NaN,NaN,NaN,0.368,NaN,0.467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,3.6,3.5,NaN,NaN,NaN,NaN,NaN,NaN,144.0,516.0,0.279,NaN,NaN,NaN,144.0,516.0,0.279,0.279,170.0,241.0,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,2,1950.0,Cliff Barker,29.0,SG,INO,49.0,NaN,NaN,NaN,0.435,NaN,0.387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6,0.6,2.2,NaN,NaN,NaN,NaN,NaN,NaN,102.0,274.0,0.372,NaN,NaN,NaN,102.0,274.0,0.372,0.372,75.0,106.0,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,3,1950.0,Leo Barnhorst,25.0,SF,CHS,67.0,NaN,NaN,NaN,0.394,NaN,0.259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9,2.8,3.6,NaN,NaN,NaN,NaN,NaN,NaN,174.0,499.0,0.349,NaN,NaN,NaN,174.0,499.0,0.349,0.349,90.0,129.0,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,4,1950.0,Ed Bartels,24.0,F,TOT,15.0,NaN,NaN,NaN,0.312,NaN,0.395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,22.0,86.0,0.256,NaN,NaN,NaN,22.0,86.0,0.256,0.256,19.0,34.0,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,5,1950.0,Ed Bartels,24.0,F,DNN,13.0,NaN,NaN,NaN,0.308,NaN,0.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,-0.1,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,21.0,82.0,0.256,NaN,NaN,NaN,21.0,82.0,0.256,0.256,17.0,31.0,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0

Last five rows:

,mergeid,Year,Player,Age,Pos,Tm,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,blanl,OWS,DWS,WS,WS/48,blank2,OBPM,DBPM,BPM,VORP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24686,24687,2017.0,Cody Zeller,24.0,PF,CHO,62.0,58.0,1725.0,16.7,0.604,0.002,0.442,8.6,17.3,12.9,9.1,1.8,3.0,10.9,15.5,NaN,3.4,2.2,5.6,0.157,NaN,-0.2,2.3,2.1,1.8,253.0,443.0,0.571,0.0,1.0,0.000,253.0,442.0,0.572,0.571,133.0,196.0,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,24688,2017.0,Tyler Zeller,27.0,C,BOS,51.0,5.0,525.0,13.0,0.508,0.006,0.247,9.2,17.0,13.2,12.2,0.7,3.3,10.2,16.5,NaN,0.5,0.6,1.0,0.094,NaN,-3.2,0.8,-2.5,-0.1,78.0,158.0,0.494,0.0,1.0,0.000,78.0,157.0,0.497,0.494,22.0,39.0,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,24689,2017.0,Stephen Zimmerman,20.0,C,ORL,19.0,0.0,108.0,7.3,0.346,0.000,0.161,10.8,24.9,17.6,5.3,0.9,3.7,8.3,14.8,NaN,-0.1,0.1,0.0,-0.005,NaN,-7.8,0.4,-7.3,-0.1,10.0,31.0,0.323,0.0,0.0,NaN,10.0,31.0,0.323,0.323,3.0,5.0,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,24690,2017.0,Paul Zipser,22.0,SF,CHI,44.0,18.0,843.0,6.9,0.503,0.448,0.181,1.9,14.2,8.0,6.1,0.9,1.5,14.4,14.4,NaN,-0.3,0.8,0.5,0.030,NaN,-3.6,-0.1,-3.7,-0.4,88.0,221.0,0.398,33.0,99.0,0.333,55.0,122.0,0.451,0.473,31.0,40.0,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,24691,2017.0,Ivica Zubac,19.0,C,LAL,38.0,11.0,609.0,17.0,0.547,0.013,0.206,7.1,21.9,14.3,8.1,1.1,4.4,10.4,20.3,NaN,0.6,0.5,1.1,0.086,NaN,-2.7,0.3,-2.5,-0.1,126.0,238.0,0.529,0.0,3.0,0.000,126.0,235.0,0.536,0.529,32.0,49.0,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

## Q10. Subset the original dataset to the years 1995-1997. Group the data by team name and year and then summarize the average number of points per team. Arrange from most to least points.

In [13]:

nba_95_97 = nba[nba['Year'].between(1995, 1997)].copy()

q10 = (
    nba_95_97.groupby(['Tm', 'Year'], dropna=False)['PTS']
    .mean()
    .reset_index(name='avg_points')
    .sort_values('avg_points', ascending=False)
    .reset_index(drop=True)
)

print("Shape:", q10.shape)

print("\nFirst five rows:")
display(q10.head())

print("\nLast five rows:")
display(q10.tail())

Shape: (88, 3)

First five rows:

    Tm    Year  avg_points
0  SEA  1996.0  659.384615
1  SEA  1995.0  646.785714
2  MIN  1997.0  606.307692
3  ORL  1995.0  606.066667
4  PHO  1995.0  604.866667

Last five rows:

     Tm    Year  avg_points
83  DEN  1997.0  348.695652
84  NJN  1997.0  346.695652
85  PHI  1996.0  322.750000
86  TOT  1997.0  322.380952
87  DAL  1997.0  275.222222

## Q11. Create a wide dataset that keeps each year in its own row, but spreads team names to multiple columns with each column delineating points per team in each of the 1995-1997 seasons.

In [ ]:
q11 = (
    nba_95_97.groupby(['Year', 'Tm'], dropna=False)['PTS']
    .mean()
    .reset_index()
    .pivot(index='Year', columns='Tm', values='PTS')
    .sort_index()
)

print("Shape:", q11.shape)

print("\nWide dataset:")
display(q11)

print("\nFirst five rows:")
display(q11.head())

print("\nLast five rows:")
display(q11.tail())

Shape: (3, 30)

Wide dataset:

Tm,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,HOU,IND,LAC,LAL,MIA,MIL,MIN,NJN,NYK,ORL,PHI,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1995.0,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,499.470588,542.400000,495.437500,538.500000,552.866667,581.857143,429.222222,536.133333,503.375000,606.066667,411.578947,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1996.0,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,466.888889,581.714286,582.357143,602.714286,359.500000,461.000000,472.000000,426.888889,468.882353,535.687500,322.750000,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
1997.0,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,458.222222,411.526316,531.266667,482.352941,409.263158,459.882353,606.307692,346.695652,601.461538,454.058824,513.437500,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

First five rows:

Tm,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,HOU,IND,LAC,LAL,MIA,MIL,MIN,NJN,NYK,ORL,PHI,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1995.0,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,499.470588,542.400000,495.437500,538.500000,552.866667,581.857143,429.222222,536.133333,503.375000,606.066667,411.578947,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1996.0,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,466.888889,581.714286,582.357143,602.714286,359.500000,461.000000,472.000000,426.888889,468.882353,535.687500,322.750000,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
1997.0,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,458.222222,411.526316,531.266667,482.352941,409.263158,459.882353,606.307692,346.695652,601.461538,454.058824,513.437500,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

Last five rows:

Tm,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,HOU,IND,LAC,LAL,MIA,MIL,MIN,NJN,NYK,ORL,PHI,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1995.0,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,499.470588,542.400000,495.437500,538.500000,552.866667,581.857143,429.222222,536.133333,503.375000,606.066667,411.578947,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1996.0,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,466.888889,581.714286,582.357143,602.714286,359.500000,461.000000,472.000000,426.888889,468.882353,535.687500,322.750000,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
1997.0,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,458.222222,411.526316,531.266667,482.352941,409.263158,459.882353,606.307692,346.695652,601.461538,454.058824,513.437500,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

## Q12. Return the data from Q11 back into a long (tidy) format by moving Team (TM), Points, and Year into their own columns.

In [15]:

q12 = (
    q11.reset_index()
    .melt(id_vars='Year', var_name='Tm', value_name='PTS')
    .sort_values(['Year', 'Tm'])
    .reset_index(drop=True)
)

print("Shape:", q12.shape)

print("\nFirst five rows:")
display(q12.head())

print("\nLast five rows:")
display(q12.tail())

Shape: (90, 3)

First five rows:

     Year   Tm         PTS
0  1995.0  ATL  440.055556
1  1995.0  BOS  495.764706
2  1995.0  CHH  515.562500
3  1995.0  CHI  520.312500
4  1995.0  CLE  494.466667

Last five rows:

      Year   Tm         PTS
85  1997.0  TOR  372.809524
86  1997.0  TOT  322.380952
87  1997.0  UTA  563.600000
88  1997.0  VAN  457.062500
89  1997.0  WSB  543.133333