# Homework 4 – Functions II

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from random import randint
from math import sqrt

## Q1. Import the data as a pd.DataFrame object. Use one or more functions from the pandas library to split the data into three unique datasets. The first should include columns that are factors only (i.e., categorical data), the second should include columns that are numeric only, and the third should include columns with logical/boolean variables only.

In [2]:
housing = pd.read_csv("Housing_prices_data.csv")
housing.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
factors_df = housing.select_dtypes(include=["object"]).copy()
numeric_df = housing.select_dtypes(include=[np.number]).copy()
logical_df = housing.select_dtypes(include=["bool"]).copy()

print("Full dataset shape:", housing.shape)
print("Factors-only shape:", factors_df.shape)
print("Numeric-only shape:", numeric_df.shape)
print("Logical-only shape:", logical_df.shape)

factors_df.head()

Full dataset shape: (1460, 81)
Factors-only shape: (1460, 42)
Numeric-only shape: (1460, 38)
Logical-only shape: (1460, 1)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

## Q2. Using the second dataset from question #1, for each numeric variable use the apply function from the pandas library to return the mean, median and standard deviation (SD) of all numeric variables.

In [5]:
numeric_summary = numeric_df.apply(["mean", "median", "std"]).T
numeric_summary.head()

                     mean  median          std
Id             730.500000   730.5   421.610009
MSSubClass      56.897260    50.0    42.300571
LotFrontage     70.049958    69.0    24.284752
LotArea      10516.828082  9478.5  9981.264932
OverallQual      6.099315     6.0     1.382997

In [6]:
numeric_summary.tail()

                    mean    median           std
PoolArea        2.758904       0.0     40.177307
MiscVal        43.489041       0.0    496.123024
MoSold          6.321918       6.0      2.703626
YrSold       2007.815753    2008.0      1.328095
SalePrice  180921.195890  163000.0  79442.502883

## Q3. Using the second dataset from question #1, create a new dataset that only includes the variable indicating sales price ("SalePrice"). Search for a categorical variable which has between 2-4 categories in the full dataset that you think may be related to the sales price of houses. Give the mean, median and SD for SalePrice based on the different groups of the categorical variables. Does the average price seem to vary by the different levels of the categorical factor you chose?

I chose **PavedDrive**, which has three categories (`Y`, `P`, `N`) and is plausibly related to house value.

In [7]:
saleprice_only = numeric_df[["SalePrice"]].copy()
saleprice_only.head()

   SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000

In [8]:
saleprice_by_paveddrive = (
    housing.groupby("PavedDrive")["SalePrice"]
    .agg(["mean", "median", "std"])
    .reset_index()
)

saleprice_by_paveddrive.head()

  PavedDrive           mean    median           std
0          N  115039.122222  111000.0  44352.523309
1          P  132330.000000  132250.0  33503.030228
2          Y  186433.973881  168500.0  79665.503047

In [9]:
saleprice_by_paveddrive.tail()

  PavedDrive           mean    median           std
0          N  115039.122222  111000.0  44352.523309
1          P  132330.000000  132250.0  33503.030228
2          Y  186433.973881  168500.0  79665.503047

**Answer:** Yes, the average sale price appears to vary across the levels of PavedDrive. Homes with paved driveways (`Y`) have the highest average sale price, homes with partial paving (`P`) are in the middle, and homes with no paved driveway (`N`) have the lowest average sale price.

## Q4. Regress "SalePrice" on "LotArea", "OverallQual", "OverallCond" with the statsmodels library. Use the syntax below to replicate the output shown you are able to estimate this regression model.

In [10]:
model_full = smf.ols("SalePrice ~ LotArea + OverallQual + OverallCond", data=housing).fit()
model_full.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.658
Method:                 Least Squares   F-statistic:                     935.9
Date:                Thu, 02 Apr 2026   Prob (F-statistic):               0.00
Time:                        02:50:51   Log-Likelihood:                -17760.
No. Observations:                1460   AIC:                         3.553e+04
Df Residuals:                    1456   BIC:                         3.555e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -1.022e+05   8633.073    -11.832      0.000   -1.19e+05   -8.52e+04
LotArea         1.4503      0.123     11.831      0.000       1.210       1.691
OverallQual   4.43e+04    888.434     49.860      0.000    4.26e+04     4.6e+04
OverallCond  -423.6737   1097.973     -0.386      0.700   -2577.451    1730.104
==============================================================================
Omnibus:                      574.483   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7330.883
Skew:                           1.468   Prob(JB):                         0.00
Kurtosis:                      13.578   Cond. No.                     1.04e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Q5. Write a for loop that loops through each level of the categorical factor you chose in Q3, where each iteration of the for loop subsets your data for one group of the categorical variable at a time, and then fits the same regression model specified above in Q4 *k* times, where *k* refers to the number of unique categories. On each iteration of your for loop, store the model.summary() information as a new element in a list object. Once your for loop is done running, print the list. There should be *k* regressions which you estimated. Does the effect of LotArea on SalePrice vary within the different levels of the categorical factor you chose? What is another, more common way to answer a question like this (i.e., a question about moderation or effect heterogeneity)?

In [11]:
model_summaries = []
coef_rows = []

for level in sorted(housing["PavedDrive"].dropna().unique()):
    subset = housing[housing["PavedDrive"] == level]
    model = smf.ols("SalePrice ~ LotArea + OverallQual + OverallCond", data=subset).fit()
    model_summaries.append(model.summary())
    coef_rows.append({
        "PavedDrive": level,
        "LotArea_coef": model.params["LotArea"],
        "LotArea_se": model.bse["LotArea"],
        "LotArea_pvalue": model.pvalues["LotArea"],
        "n": int(model.nobs)
    })

print(model_summaries)

[<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.500
Model:                            OLS   Adj. R-squared:                  0.483
Method:                 Least Squares   F-statistic:                     28.70
Date:                Thu, 02 Apr 2026   Prob (F-statistic):           5.92e-13
Time:                        02:50:58   Log-Likelihood:                -1059.0
No. Observations:                  90   AIC:                             2126.
Df Residuals:                      86   BIC:                             2136.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -2.393e+04   1.64e+04     -1.460      0.148   -5.65e+04    8647.395
LotArea         2.3945      0.482      4.967      0.000       1.436       3.353
OverallQual  1.818e+04   3280.933      5.542      0.000    1.17e+04    2.47e+04
OverallCond  4455.3108   2209.319      2.017      0.047      63.330    8847.292
==============================================================================
Omnibus:                        5.623   Durbin-Watson:                   2.076
Prob(Omnibus):                  0.060   Jarque-Bera (JB):                4.929
Skew:                           0.496   Prob(JB):                       0.0851
Kurtosis:                       3.574   Cond. No.                     5.93e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.93e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
""", <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.588
Model:                            OLS   Adj. R-squared:                  0.541
Method:                 Least Squares   F-statistic:                     12.37
Date:                Thu, 02 Apr 2026   Prob (F-statistic):           3.23e-05
Time:                        02:50:58   Log-Likelihood:                -341.34
No. Observations:                  30   AIC:                             690.7
Df Residuals:                      26   BIC:                             696.3
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    9536.2313   2.46e+04      0.388      0.701   -4.09e+04       6e+04
LotArea         3.0508      0.651      4.685      0.000       1.712       4.389
OverallQual  1.014e+04   4881.731      2.078      0.048     110.347    2.02e+04
OverallCond  5512.0532   3551.751      1.552      0.133   -1788.675    1.28e+04
==============================================================================
Omnibus:                        0.480   Durbin-Watson:                   2.576
Prob(Omnibus):                  0.787   Jarque-Bera (JB):                0.321
Skew:                           0.242   Prob(JB):                        0.852
Kurtosis:                       2.847   Cond. No.                     7.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
""", <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.657
Model:                            OLS   Adj. R-squared:                  0.656
Method:                 Least Squares   F-statistic:                     853.3
Date:                Thu, 02 Apr 2026   Prob (F-statistic):          7.87e-310
Time:                        02:50:58   Log-Likelihood:                -16307.
No. Observations:                1340   AIC:                         3.262e+04
Df Residuals:                    1336   BIC:                         3.264e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -1.132e+05   9692.960    -11.674      0.000   -1.32e+05   -9.41e+04
LotArea         1.4110      0.126     11.220      0.000       1.164       1.658
OverallQual  4.512e+04    950.354     47.480      0.000    4.33e+04     4.7e+04
OverallCond   945.5313   1228.306      0.770      0.442   -1464.087    3355.149
==============================================================================
Omnibus:                      545.323   Durbin-Watson:                   1.958
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7100.080
Skew:                           1.521   Prob(JB):                         0.00
Kurtosis:                      13.859   Cond. No.                     1.12e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""]

In [12]:
coef_comparison = pd.DataFrame(coef_rows)
coef_comparison.head()

  PavedDrive  LotArea_coef  LotArea_se  LotArea_pvalue     n
0          N      2.394493    0.482076    3.415476e-06    90
1          P      3.050797    0.651206    7.723031e-05    30
2          Y      1.410988    0.125756    5.545305e-28  1340

In [13]:
coef_comparison.tail()

  PavedDrive  LotArea_coef  LotArea_se  LotArea_pvalue     n
0          N      2.394493    0.482076    3.415476e-06    90
1          P      3.050797    0.651206    7.723031e-05    30
2          Y      1.410988    0.125756    5.545305e-28  1340

**Answer:** The estimated effect of LotArea on SalePrice does vary across the PavedDrive groups, but the size of the difference should be interpreted together with the standard errors, not by coefficient values alone. A more common way to test moderation or effect heterogeneity is to fit a single regression with interaction terms, such as `SalePrice ~ LotArea * C(PavedDrive) + OverallQual + OverallCond`.

## Q6.  Using the first dataset from question #1, for each categorical variable use a for loop to print a frequency and relative frequency table for every variable. To make your output readable, for each variable you should print the following in this order, placing the variable name where you see blanks below.

In [14]:
for col in factors_df.columns:
    print(f"Frequency table for {col} ============")
    print(factors_df[col].value_counts(dropna=False))
    print()
    print(f"Relative frequency table for {col} ============")
    print(factors_df[col].value_counts(dropna=False, normalize=True))
    print("\n\n")

Frequency table for MSZoning ============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative frequency table for MSZoning ============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64



Frequency table for Street ============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative frequency table for Street ============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64



Frequency table for Alley ============
Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

Relative frequency table for Alley ============
Alley
NaN     0.937671
Grvl    0.034247
Pave    0.028082
Name: proportion, dtype: float64



Frequency table for LotShape ============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative frequency table for LotShape ============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64



Frequency table for LandContour ============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative frequency table for LandContour ============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64



Frequency table for Utilities ============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative frequency table for Utilities ============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64



Frequency table for LotConfig ============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative frequency table for LotConfig ============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64



Frequency table for LandSlope ============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative frequency table for LandSlope ============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64



Frequency table for Neighborhood ============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative frequency table for Neighborhood ============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
SWISU      0.017123
StoneBr    0.017123
Blmngtn    0.011644
MeadowV    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64



Frequency table for Condition1 ============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative frequency table for Condition1 ============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64



Frequency table for Condition2 ============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative frequency table for Condition2 ============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64



Frequency table for BldgType ============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative frequency table for BldgType ============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64



Frequency table for HouseStyle ============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative frequency table for HouseStyle ============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64



Frequency table for RoofStyle ============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative frequency table for RoofStyle ============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64



Frequency table for RoofMatl ============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative frequency table for RoofMatl ============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64



Frequency table for Exterior1st ============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior1st ============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for Exterior2nd ============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior2nd ============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for MasVnrType ============
MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative frequency table for MasVnrType ============
MasVnrType
NaN        0.597260
BrkFace    0.304795
Stone      0.087671
BrkCmn     0.010274
Name: proportion, dtype: float64



Frequency table for ExterQual ============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative frequency table for ExterQual ============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64



Frequency table for ExterCond ============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative frequency table for ExterCond ============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Foundation ============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative frequency table for Foundation ============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64



Frequency table for BsmtQual ============
BsmtQual
TA     649
Gd     618
Ex     121
NaN     37
Fa      35
Name: count, dtype: int64

Relative frequency table for BsmtQual ============
BsmtQual
TA     0.444521
Gd     0.423288
Ex     0.082877
NaN    0.025342
Fa     0.023973
Name: proportion, dtype: float64



Frequency table for BsmtCond ============
BsmtCond
TA     1311
Gd       65
Fa       45
NaN      37
Po        2
Name: count, dtype: int64

Relative frequency table for BsmtCond ============
BsmtCond
TA     0.897945
Gd     0.044521
Fa     0.030822
NaN    0.025342
Po     0.001370
Name: proportion, dtype: float64



Frequency table for BsmtExposure ============
BsmtExposure
No     953
Av     221
Gd     134
Mn     114
NaN     38
Name: count, dtype: int64

Relative frequency table for BsmtExposure ============
BsmtExposure
No     0.652740
Av     0.151370
Gd     0.091781
Mn     0.078082
NaN    0.026027
Name: proportion, dtype: float64



Frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
NaN     37
Name: count, dtype: int64

Relative frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    0.294521
GLQ    0.286301
ALQ    0.150685
BLQ    0.101370
Rec    0.091096
LwQ    0.050685
NaN    0.025342
Name: proportion, dtype: float64



Frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
NaN      38
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    0.860274
Rec    0.036986
LwQ    0.031507
NaN    0.026027
BLQ    0.022603
ALQ    0.013014
GLQ    0.009589
Name: proportion, dtype: float64



Frequency table for Heating ============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative frequency table for Heating ============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64



Frequency table for HeatingQC ============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative frequency table for HeatingQC ============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Electrical ============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
NaN         1
Name: count, dtype: int64

Relative frequency table for Electrical ============
Electrical
SBrkr    0.913699
FuseA    0.064384
FuseF    0.018493
FuseP    0.002055
Mix      0.000685
NaN      0.000685
Name: proportion, dtype: float64



Frequency table for KitchenQual ============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative frequency table for KitchenQual ============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64



Frequency table for Functional ============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative frequency table for Functional ============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64



Frequency table for FireplaceQu ============
FireplaceQu
NaN    690
Gd     380
TA     313
Fa      33
Ex      24
Po      20
Name: count, dtype: int64

Relative frequency table for FireplaceQu ============
FireplaceQu
NaN    0.472603
Gd     0.260274
TA     0.214384
Fa     0.022603
Ex     0.016438
Po     0.013699
Name: proportion, dtype: float64



Frequency table for GarageType ============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
NaN         81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative frequency table for GarageType ============
GarageType
Attchd     0.595890
Detchd     0.265068
BuiltIn    0.060274
NaN        0.055479
Basment    0.013014
CarPort    0.006164
2Types     0.004110
Name: proportion, dtype: float64



Frequency table for GarageFinish ============
GarageFinish
Unf    605
RFn    422
Fin    352
NaN     81
Name: count, dtype: int64

Relative frequency table for GarageFinish ============
GarageFinish
Unf    0.414384
RFn    0.289041
Fin    0.241096
NaN    0.055479
Name: proportion, dtype: float64



Frequency table for GarageQual ============
GarageQual
TA     1311
NaN      81
Fa       48
Gd       14
Ex        3
Po        3
Name: count, dtype: int64

Relative frequency table for GarageQual ============
GarageQual
TA     0.897945
NaN    0.055479
Fa     0.032877
Gd     0.009589
Ex     0.002055
Po     0.002055
Name: proportion, dtype: float64



Frequency table for GarageCond ============
GarageCond
TA     1326
NaN      81
Fa       35
Gd        9
Po        7
Ex        2
Name: count, dtype: int64

Relative frequency table for GarageCond ============
GarageCond
TA     0.908219
NaN    0.055479
Fa     0.023973
Gd     0.006164
Po     0.004795
Ex     0.001370
Name: proportion, dtype: float64



Frequency table for PavedDrive ============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative frequency table for PavedDrive ============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64



Frequency table for PoolQC ============
PoolQC
NaN    1453
Gd        3
Ex        2
Fa        2
Name: count, dtype: int64

Relative frequency table for PoolQC ============
PoolQC
NaN    0.995205
Gd     0.002055
Ex     0.001370
Fa     0.001370
Name: proportion, dtype: float64



Frequency table for Fence ============
Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

Relative frequency table for Fence ============
Fence
NaN      0.807534
MnPrv    0.107534
GdPrv    0.040411
GdWo     0.036986
MnWw     0.007534
Name: proportion, dtype: float64



Frequency table for MiscFeature ============
MiscFeature
NaN     1406
Shed      49
Gar2       2
Othr       2
TenC       1
Name: count, dtype: int64

Relative frequency table for MiscFeature ============
MiscFeature
NaN     0.963014
Shed    0.033562
Gar2    0.001370
Othr    0.001370
TenC    0.000685
Name: proportion, dtype: float64



Frequency table for SaleType ============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative frequency table for SaleType ============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64



Frequency table for SaleCondition ============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative frequency table for SaleCondition ============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

## Q7. Do the same thing as number 6, but with a while loop this time.

In [15]:
i = 0
factor_cols = list(factors_df.columns)

while i < len(factor_cols):
    col = factor_cols[i]
    print(f"Frequency table for {col} ============")
    print(factors_df[col].value_counts(dropna=False))
    print()
    print(f"Relative frequency table for {col} ============")
    print(factors_df[col].value_counts(dropna=False, normalize=True))
    print("\n\n")
    i += 1

Frequency table for MSZoning ============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative frequency table for MSZoning ============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64



Frequency table for Street ============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative frequency table for Street ============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64



Frequency table for Alley ============
Alley
NaN     1369
Grvl      50
Pave      41
Name: count, dtype: int64

Relative frequency table for Alley ============
Alley
NaN     0.937671
Grvl    0.034247
Pave    0.028082
Name: proportion, dtype: float64



Frequency table for LotShape ============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative frequency table for LotShape ============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64



Frequency table for LandContour ============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative frequency table for LandContour ============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64



Frequency table for Utilities ============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative frequency table for Utilities ============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64



Frequency table for LotConfig ============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative frequency table for LotConfig ============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64



Frequency table for LandSlope ============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative frequency table for LandSlope ============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64



Frequency table for Neighborhood ============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative frequency table for Neighborhood ============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
SWISU      0.017123
StoneBr    0.017123
Blmngtn    0.011644
MeadowV    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64



Frequency table for Condition1 ============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative frequency table for Condition1 ============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64



Frequency table for Condition2 ============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative frequency table for Condition2 ============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64



Frequency table for BldgType ============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative frequency table for BldgType ============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64



Frequency table for HouseStyle ============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative frequency table for HouseStyle ============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64



Frequency table for RoofStyle ============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative frequency table for RoofStyle ============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64



Frequency table for RoofMatl ============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative frequency table for RoofMatl ============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64



Frequency table for Exterior1st ============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior1st ============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for Exterior2nd ============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior2nd ============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for MasVnrType ============
MasVnrType
NaN        872
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative frequency table for MasVnrType ============
MasVnrType
NaN        0.597260
BrkFace    0.304795
Stone      0.087671
BrkCmn     0.010274
Name: proportion, dtype: float64



Frequency table for ExterQual ============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative frequency table for ExterQual ============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64



Frequency table for ExterCond ============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative frequency table for ExterCond ============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Foundation ============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative frequency table for Foundation ============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64



Frequency table for BsmtQual ============
BsmtQual
TA     649
Gd     618
Ex     121
NaN     37
Fa      35
Name: count, dtype: int64

Relative frequency table for BsmtQual ============
BsmtQual
TA     0.444521
Gd     0.423288
Ex     0.082877
NaN    0.025342
Fa     0.023973
Name: proportion, dtype: float64



Frequency table for BsmtCond ============
BsmtCond
TA     1311
Gd       65
Fa       45
NaN      37
Po        2
Name: count, dtype: int64

Relative frequency table for BsmtCond ============
BsmtCond
TA     0.897945
Gd     0.044521
Fa     0.030822
NaN    0.025342
Po     0.001370
Name: proportion, dtype: float64



Frequency table for BsmtExposure ============
BsmtExposure
No     953
Av     221
Gd     134
Mn     114
NaN     38
Name: count, dtype: int64

Relative frequency table for BsmtExposure ============
BsmtExposure
No     0.652740
Av     0.151370
Gd     0.091781
Mn     0.078082
NaN    0.026027
Name: proportion, dtype: float64



Frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
NaN     37
Name: count, dtype: int64

Relative frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    0.294521
GLQ    0.286301
ALQ    0.150685
BLQ    0.101370
Rec    0.091096
LwQ    0.050685
NaN    0.025342
Name: proportion, dtype: float64



Frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
NaN      38
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    0.860274
Rec    0.036986
LwQ    0.031507
NaN    0.026027
BLQ    0.022603
ALQ    0.013014
GLQ    0.009589
Name: proportion, dtype: float64



Frequency table for Heating ============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative frequency table for Heating ============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64



Frequency table for HeatingQC ============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative frequency table for HeatingQC ============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Electrical ============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
NaN         1
Name: count, dtype: int64

Relative frequency table for Electrical ============
Electrical
SBrkr    0.913699
FuseA    0.064384
FuseF    0.018493
FuseP    0.002055
Mix      0.000685
NaN      0.000685
Name: proportion, dtype: float64



Frequency table for KitchenQual ============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative frequency table for KitchenQual ============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64



Frequency table for Functional ============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative frequency table for Functional ============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64



Frequency table for FireplaceQu ============
FireplaceQu
NaN    690
Gd     380
TA     313
Fa      33
Ex      24
Po      20
Name: count, dtype: int64

Relative frequency table for FireplaceQu ============
FireplaceQu
NaN    0.472603
Gd     0.260274
TA     0.214384
Fa     0.022603
Ex     0.016438
Po     0.013699
Name: proportion, dtype: float64



Frequency table for GarageType ============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
NaN         81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative frequency table for GarageType ============
GarageType
Attchd     0.595890
Detchd     0.265068
BuiltIn    0.060274
NaN        0.055479
Basment    0.013014
CarPort    0.006164
2Types     0.004110
Name: proportion, dtype: float64



Frequency table for GarageFinish ============
GarageFinish
Unf    605
RFn    422
Fin    352
NaN     81
Name: count, dtype: int64

Relative frequency table for GarageFinish ============
GarageFinish
Unf    0.414384
RFn    0.289041
Fin    0.241096
NaN    0.055479
Name: proportion, dtype: float64



Frequency table for GarageQual ============
GarageQual
TA     1311
NaN      81
Fa       48
Gd       14
Ex        3
Po        3
Name: count, dtype: int64

Relative frequency table for GarageQual ============
GarageQual
TA     0.897945
NaN    0.055479
Fa     0.032877
Gd     0.009589
Ex     0.002055
Po     0.002055
Name: proportion, dtype: float64



Frequency table for GarageCond ============
GarageCond
TA     1326
NaN      81
Fa       35
Gd        9
Po        7
Ex        2
Name: count, dtype: int64

Relative frequency table for GarageCond ============
GarageCond
TA     0.908219
NaN    0.055479
Fa     0.023973
Gd     0.006164
Po     0.004795
Ex     0.001370
Name: proportion, dtype: float64



Frequency table for PavedDrive ============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative frequency table for PavedDrive ============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64



Frequency table for PoolQC ============
PoolQC
NaN    1453
Gd        3
Ex        2
Fa        2
Name: count, dtype: int64

Relative frequency table for PoolQC ============
PoolQC
NaN    0.995205
Gd     0.002055
Ex     0.001370
Fa     0.001370
Name: proportion, dtype: float64



Frequency table for Fence ============
Fence
NaN      1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

Relative frequency table for Fence ============
Fence
NaN      0.807534
MnPrv    0.107534
GdPrv    0.040411
GdWo     0.036986
MnWw     0.007534
Name: proportion, dtype: float64



Frequency table for MiscFeature ============
MiscFeature
NaN     1406
Shed      49
Gar2       2
Othr       2
TenC       1
Name: count, dtype: int64

Relative frequency table for MiscFeature ============
MiscFeature
NaN     0.963014
Shed    0.033562
Gar2    0.001370
Othr    0.001370
TenC    0.000685
Name: proportion, dtype: float64



Frequency table for SaleType ============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative frequency table for SaleType ============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64



Frequency table for SaleCondition ============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative frequency table for SaleCondition ============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

## Q8. Using the Rocket class which we created as part of the week 7 class activity, we are going to create a new class called shuttle. The shuttle class should inherit all of Rocket's characteristics but has one additional parameter: flights_completed which measures the number of flights the shuttle has completed.

In [16]:
class Rocket:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def distance_from(self, other):
        return round(sqrt((self.x - other.x)**2 + (self.y - other.y)**2), 2)


class Shuttle(Rocket):
    def __init__(self, x, y, flights_completed):
        super().__init__(x, y)
        self.flights_completed = flights_completed

In [17]:
my_shuttle = Shuttle(12, 8, 5)
print(f"The shuttle is located at ({my_shuttle.x}, {my_shuttle.y}), and has recorded {my_shuttle.flights_completed} flights")

The shuttle is located at (12, 8), and has recorded 5 flights

## Q9. Write a single for loop which randomly creates 11 rockets and 11 shuttles using randomly generated integers. Store this output in two separate lists. Once you have your data, use for loops to print the messages you see below. Note you can use the randint() function from the random module (which you can import with the command from random import randint) to randomly generate the characteristics of your Rockets and Shuttles.

In [18]:
rockets = []
shuttles = []

for _ in range(11):
    rockets.append(Rocket(randint(0, 100), randint(0, 100)))
    shuttles.append(Shuttle(randint(0, 100), randint(0, 100), randint(0, 10)))

print("Number of rockets:", len(rockets))
print("Number of shuttles:", len(shuttles))

Number of rockets: 11
Number of shuttles: 11

In [19]:
for i, shuttle in enumerate(shuttles):
    print(f"Shuttle {i} has completed {shuttle.flights_completed} flights.")

Shuttle 0 has completed 10 flights.
Shuttle 1 has completed 8 flights.
Shuttle 2 has completed 5 flights.
Shuttle 3 has completed 7 flights.
Shuttle 4 has completed 6 flights.
Shuttle 5 has completed 6 flights.
Shuttle 6 has completed 3 flights.
Shuttle 7 has completed 0 flights.
Shuttle 8 has completed 1 flights.
Shuttle 9 has completed 4 flights.
Shuttle 10 has completed 1 flights.

In [20]:
first_shuttle = shuttles[0]

for i, shuttle in enumerate(shuttles):
    distance = first_shuttle.distance_from(shuttle)
    print(f"The first shuttle is {distance} units away from shuttle {i}.")

The first shuttle is 0.0 units away from shuttle 0.
The first shuttle is 57.94 units away from shuttle 1.
The first shuttle is 26.08 units away from shuttle 2.
The first shuttle is 38.9 units away from shuttle 3.
The first shuttle is 26.91 units away from shuttle 4.
The first shuttle is 35.9 units away from shuttle 5.
The first shuttle is 28.84 units away from shuttle 6.
The first shuttle is 38.21 units away from shuttle 7.
The first shuttle is 78.77 units away from shuttle 8.
The first shuttle is 67.88 units away from shuttle 9.
The first shuttle is 37.36 units away from shuttle 10.

In [21]:
for i, rocket in enumerate(rockets):
    distance = first_shuttle.distance_from(rocket)
    print(f"The first shuttle is {distance} units away from rocket {i}.")

The first shuttle is 15.62 units away from rocket 0.
The first shuttle is 58.6 units away from rocket 1.
The first shuttle is 29.83 units away from rocket 2.
The first shuttle is 42.06 units away from rocket 3.
The first shuttle is 98.41 units away from rocket 4.
The first shuttle is 38.08 units away from rocket 5.
The first shuttle is 66.1 units away from rocket 6.
The first shuttle is 2.24 units away from rocket 7.
The first shuttle is 76.24 units away from rocket 8.
The first shuttle is 61.2 units away from rocket 9.
The first shuttle is 22.67 units away from rocket 10.